import React, { useMemo, useState } from "react";
import {
  Pressable,
  SafeAreaView,
  StyleSheet,
  Text,
  View,
} from "react-native";
import MapView, { Marker, Polyline } from "react-native-maps";
import Slider from "@react-native-community/slider";
import * as Haptics from "expo-haptics";

import {
  buildGraph,
  GraphData,
  nearestNode,
  Route,
  seasonDate,
  shortestRoute,
} from "./src/graph";
import { meltEmoji, meltLabel, meltPct, MOODS, savingsCopy } from "./src/melt";

// Precomputed shade graph (generated by pipeline/precompute.py)
const graphData: GraphData = require("./assets/singapore.json");

const SHADE_COLOR = "#0E9594";
const SUN_COLOR = "#FF7A2F";
const FASTEST_COLOR = "#9AA0A6";
const INK = "#1F2430";

function expColor(exposure: number): string {
  // teal (shade) -> orange (full sun)
  const t = Math.min(1, Math.max(0, exposure));
  const a = [14, 149, 148];
  const b = [255, 122, 47];
  const c = a.map((x, i) => Math.round(x + (b[i] - x) * t));
  return `rgb(${c[0]},${c[1]},${c[2]})`;
}

type Pt = { latitude: number; longitude: number };

export default function App() {
  const graph = useMemo(() => buildGraph(graphData), []);
  const { bbox, hours, dates, tz_offset_hours } = graphData.meta;

  const initialRegion = {
    latitude: (bbox[1] + bbox[3]) / 2,
    longitude: (bbox[0] + bbox[2]) / 2,
    latitudeDelta: (bbox[3] - bbox[1]) * 1.2,
    longitudeDelta: (bbox[2] - bbox[0]) * 1.2,
  };

  const nowLocal = new Date(
    Date.now() + (tz_offset_hours * 60 + new Date().getTimezoneOffset()) * 60_000,
  );
  const defaultHour = Math.min(hours[hours.length - 1], Math.max(hours[0], nowLocal.getHours()));

  const [start, setStart] = useState<Pt | null>(null);
  const [end, setEnd] = useState<Pt | null>(null);
  const [hour, setHour] = useState(defaultHour);
  const [moodIdx, setMoodIdx] = useState(1);

  const date = useMemo(() => seasonDate(dates, nowLocal), [dates]);
  const hourIdx = hours.indexOf(hour);

  const routes = useMemo(() => {
    if (!start || !end) return null;
    const a = nearestNode(graph, start.latitude, start.longitude);
    const b = nearestNode(graph, end.latitude, end.longitude);
    if (a.distM > 400 || b.distM > 400) return { outside: true } as const;
    const fastest = shortestRoute(graph, a.node, b.node, date, hourIdx, 0);
    const shady = shortestRoute(graph, a.node, b.node, date, hourIdx, MOODS[moodIdx].weight);
    if (!fastest || !shady) return null;
    return { outside: false, fastest, shady } as const;
  }, [graph, start, end, date, hourIdx, moodIdx]);

  const onTap = (pt: Pt) => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    if (!start || (start && end)) {
      setStart(pt);
      setEnd(null);
    } else {
      setEnd(pt);
    }
  };

  const fastest = routes && !routes.outside ? routes.fastest : null;
  const shady = routes && !routes.outside ? routes.shady : null;
  const fastMelt = fastest ? meltPct(fastest.sunMin) : 0;
  const shadyMelt = shady ? meltPct(shady.sunMin) : 0;

  return (
    <View style={styles.container}>
      <MapView
        style={StyleSheet.absoluteFill}
        initialRegion={initialRegion}
        onPress={(e) => onTap(e.nativeEvent.coordinate)}
        onLongPress={() => {
          setStart(null);
          setEnd(null);
        }}
      >
        {fastest && (
          <Polyline
            coordinates={routeCoords(fastest)}
            strokeColor={FASTEST_COLOR}
            strokeWidth={4}
            lineDashPattern={[8, 6]}
          />
        )}
        {shady &&
          shady.segments.map((s, i) => (
            <Polyline
              key={i}
              coordinates={s.coords.map(([lon, lat]) => ({ latitude: lat, longitude: lon }))}
              strokeColor={expColor(s.exposure)}
              strokeWidth={6}
            />
          ))}
        {start && (
          <Marker coordinate={start} anchor={{ x: 0.5, y: 0.5 }}>
            <Text style={styles.markerEmoji}>🧍</Text>
          </Marker>
        )}
        {end && (
          <Marker coordinate={end} anchor={{ x: 0.5, y: 0.5 }}>
            <Text style={styles.markerEmoji}>🎯</Text>
          </Marker>
        )}
      </MapView>

      <SafeAreaView style={styles.overlay} pointerEvents="box-none">
        {/* time slider */}
        <View style={styles.topCard}>
          <Text style={styles.topLabel}>
            ☀️ {String(hour).padStart(2, "0")}:00 · Singapore
          </Text>
          <Slider
            minimumValue={hours[0]}
            maximumValue={hours[hours.length - 1]}
            step={1}
            value={hour}
            onValueChange={setHour}
            minimumTrackTintColor={SUN_COLOR}
            maximumTrackTintColor="#E8E2D4"
            thumbTintColor={SUN_COLOR}
          />
        </View>

        <View pointerEvents="box-none" style={{ flex: 1 }} />

        {/* bottom panel */}
        <View style={styles.bottomCard}>
          {!start && <Text style={styles.hint}>Tap the map to drop your start 🧍</Text>}
          {start && !end && <Text style={styles.hint}>Now tap your destination 🎯</Text>}
          {routes?.outside && (
            <Text style={styles.hint}>That's outside the demo area — try the CBD 🙏</Text>
          )}

          {fastest && shady && (
            <>
              <View style={styles.routesRow}>
                <View style={[styles.routePill, { borderColor: FASTEST_COLOR }]}>
                  <Text style={styles.routeTitle}>Fastest 🏃</Text>
                  <Text style={styles.routeTime}>{Math.round(fastest.walkMin)} min</Text>
                  <Text style={styles.routeMelt}>
                    {meltEmoji(fastMelt)} {fastMelt}% melted
                  </Text>
                </View>
                <View style={[styles.routePill, styles.shadyPill]}>
                  <Text style={styles.routeTitle}>Shady 🌴</Text>
                  <Text style={styles.routeTime}>{Math.round(shady.walkMin)} min</Text>
                  <Text style={styles.routeMelt}>
                    {meltEmoji(shadyMelt)} {shadyMelt}% melted
                  </Text>
                </View>
              </View>
              <Text style={styles.savings}>
                {savingsCopy(shady.walkMin - fastest.walkMin, fastest.sunMin - shady.sunMin)}
              </Text>
              <Text style={styles.meltLabel}>
                You'd arrive {meltLabel(shadyMelt)} {meltEmoji(shadyMelt)}
              </Text>
            </>
          )}

          {/* mood selector */}
          <View style={styles.moodRow}>
            {MOODS.map((m, i) => (
              <Pressable
                key={m.key}
                onPress={() => {
                  Haptics.selectionAsync();
                  setMoodIdx(i);
                }}
                style={[styles.moodBtn, i === moodIdx && styles.moodBtnActive]}
              >
                <Text style={styles.moodEmoji}>{m.emoji}</Text>
                <Text style={[styles.moodText, i === moodIdx && styles.moodTextActive]}>
                  {m.label}
                </Text>
              </Pressable>
            ))}
          </View>
        </View>
      </SafeAreaView>
    </View>
  );
}

function routeCoords(r: Route): Pt[] {
  const out: Pt[] = [];
  for (const s of r.segments) {
    for (const [lon, lat] of s.coords) out.push({ latitude: lat, longitude: lon });
  }
  return out;
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  overlay: { flex: 1, margin: 12 },
  markerEmoji: { fontSize: 30 },
  topCard: {
    backgroundColor: "rgba(255,251,240,0.95)",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  topLabel: { fontSize: 15, fontWeight: "700", color: INK },
  bottomCard: {
    backgroundColor: "rgba(255,251,240,0.97)",
    borderRadius: 22,
    padding: 14,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  hint: { fontSize: 15, fontWeight: "600", color: INK, textAlign: "center", padding: 6 },
  routesRow: { flexDirection: "row", gap: 10 },
  routePill: {
    flex: 1,
    borderWidth: 2,
    borderRadius: 16,
    padding: 10,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  shadyPill: { borderColor: SHADE_COLOR, backgroundColor: "#EAF7F6" },
  routeTitle: { fontSize: 13, fontWeight: "800", color: INK },
  routeTime: { fontSize: 22, fontWeight: "800", color: INK },
  routeMelt: { fontSize: 13, fontWeight: "600", color: INK, marginTop: 2 },
  savings: { textAlign: "center", marginTop: 10, fontSize: 14, fontWeight: "700", color: INK },
  meltLabel: { textAlign: "center", marginTop: 2, fontSize: 13, color: "#5A6072" },
  moodRow: { flexDirection: "row", gap: 8, marginTop: 12 },
  moodBtn: {
    flex: 1,
    alignItems: "center",
    borderRadius: 14,
    paddingVertical: 8,
    backgroundColor: "#F2EDE0",
  },
  moodBtnActive: { backgroundColor: INK },
  moodEmoji: { fontSize: 20 },
  moodText: { fontSize: 12, fontWeight: "700", color: "#5A6072" },
  moodTextActive: { color: "#FFFBF0" },
});
